### ISSUE TITLE
I'd like to manage this plugin under Sketch Runner

### ISSUE THREAD

**Issue by usa619** [wantedly/sketch-wt-elevation#2]
## Why
Sketch Runner: https://sketchrunner.com/

Sketch Runner is a launcher plugin which allows you to manage plugins (install, update, delete) and actions you can do within Sketch, which is a popular plugin in Sketch community.
So I'd like you to make this plugin support to Sketch Runner 

## What
Please refer this: https://sketchrunner.com/developers.html

**Comment by luvtechno** [comment]
> Install plugins
> You can browse, install, update and uninstall plugins right inside Runner. Just search for a plugin name or GitHub username.

For plugin installation to work, I believe the plugin has to be registered on the directory https://github.com/sketchplugins/plugin-directory, which I will do after 1.0.0 release.

**Comment by usa619** [comment]
Thanks  🙌

**Comment by luvtechno** [comment]
I've just released 0.1.1 -- https://github.com/wantedly/sketch-wt-design/releases

@usa619 Can you check if the runner plugin shows an icon?

**Comment by usa619** [comment]
You mean this?

<img width="680" alt="2018-08-06 11 28 53" src="https://user-images.githubusercontent.com/13025472/43693996-1160f1ca-996c-11e8-8bbe-d0e9dcf86cda.png">

**Comment by luvtechno** [comment]
No. I've set the "W" icon in the manifest file.

**Comment by usa619** [comment]
I couldn't find it out even using the latest version... 😢

**Comment by luvtechno** [comment]
https://github.com/sketchplugins/plugin-directory/pull/612 is merged! 

The plugin is available on "install" tab now:  


![image](https://user-images.githubusercontent.com/43811/44648056-d7ba9100-aa1a-11e8-8490-1c8609feeac5.png)

**Comment by usa619** [comment]
🙌 🎉 

Thank you!! and I'll close this issue
